name: PipeLine
# This workflow is triggered on pushes to the repository.
on:
  pull_request:
  push:
    branches:
      - master
      - dev

jobs:
  test:
    name: Setting Up
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    env:
      NODE_ENV: test

    steps:
    - name: Cloning Repo
      uses: actions/checkout@v1
    - name: Dependencies
      run: echo "Installing Dependecies"
    - uses: actions/setup-node@v1.1.0
    - run: npm install
    - run: npm run lint
