name: PipeLine
# This workflow is triggered on pushes to the repository.
on:
  pull_request:
  push:
    branches:
      - master
      - dev

jobs:
  test:
    name: Testing
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    env:
      NODE_ENV: test

    steps:
    - uses: actions/checkout@v1

    - uses: actions/setup-node@v1.1.0
    - run: echo "Installing Dependecies"
    - run: npm install
    - run: echo "Check Code Styling"
    - run: npm run lint
    
    - name: Setup PostgreSQL
      uses: Harmon758/postgresql-action@v1.0.0
      with:
        postgresql version: latest
        postgresql db: test_db 
        postgresql user: default is 
        postgresql password: default 
