name: PipeLine
# This workflow is triggered on pushes to the repository.
on:
  pull_request:
  push:
    branches:
      - master
      - dev

jobs:
  ci:
    runs-on: ubuntu-latest
    container: 
      image: node:12
    services:
      postgres:
        image: postgres:12-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: jy95
          POSTGRES_DB: sourcecode
    env:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: jy95
      POSTGRES_DB: sourcecode
      POSTGRES_HOST: postgres

    steps:
      - uses: actions/setup-node@v1.1.0
      - name: Set DB Port
        env:
          POSTGRES_PORT: ${{ job.services.postgres.ports[5432] }}
        run: |
          echo "::set-env name=POSTGRES_PORT::$POSTGRES_PORT"
      - name: Install
        run: |
          npm install -g npm@latest
          npm run lint
          npm run start-dev
#     - uses: actions/setup-node@v1.1.0
#     - run: echo "Installing Dependecies"
#     - run: npm install
#     - run: echo "Check Code Styling"
#     - run: npm run lint
    
#     - name: Setup PostgreSQL
#       uses: Harmon758/postgresql-action@v1.0.0
#       with:
#         postgresql version: 11
#         postgresql db: test_db 
#         postgresql user: default 
#         postgresql password: default

#     - run: npm run migrate
