name: Source Code CI/CD

on:
  push:
    # paths: 
    #   - '!**.spec.js'
    #   - '!**.test.js'
    #   - '!**.md'
    #   - '!**.yaml'
    branches:
      - master
      - qa
  pull_request:
    branches:
      - master
      - qa

jobs:
  # test:
  #   runs-on: ubuntu-latest
  #   container:
  #     image: node:12
  #   services:
  #     postgres:
  #       image: postgres:12-alpine
  #       env:
  #         POSTGRES_USER: postgres
  #         POSTGRES_PASSWORD: jy95
  #         POSTGRES_DB: sourcecode
  #       ports: ["5432:5432"]
  #       options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
  #   env:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: jy95
  #     POSTGRES_DB: sourcecode
  #     POSTGRES_HOST: postgres
  #     NODE_ENV: test
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Set DB Port
  #       env:
  #         POSTGRES_PORT: ${{ job.services.postgres.ports[5432] }}
  #       run: |
  #         echo "::set-env name=POSTGRES_PORT::$POSTGRES_PORT"
  #     - name: Install
  #       run: |
  #         npm install -g npm@latest
  #         npm install
  #     - name: Testing - Migrating & Seeding
  #       env:
  #         TEST_DATABASE_URL: 'postgresql://${{ env.POSTGRES_USER }}:${{ env.POSTGRES_PASSWORD }}@${{ env.POSTGRES_HOST }}:${{env.POSTGRES_PORT}}/${{env.POSTGRES_DB}}'
  #       run: |
  #         npm run pretest
  #         npm run seed
  #         npm run test
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    # needs: test
    # if: github.event_name == 'push' && (github.ref == 'refs/heads/master' || github.ref == 'refs/heads/dev')
    env:
      HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}
      HEROKU_EMAIL: ${{ secrets.HEROKU_EMAIL }}

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Set QA Environment
        run: echo "::set-env name=ENVIRONMENT::qa"

      - name: Set Production Environment
        if: github.ref == 'refs/heads/master'
        run: echo "::set-env name=ENVIRONMENT::prod"

      - name: Configure Heroku
        run: heroku config:set GIT_HASH=${GITHUB_SHA} GIT_BRANCH=${GITHUB_REF} --app $HEROKU_APP_NAME-$ENVIRONMENT

      # - name: Push to Heroku
      #   run: git push --force https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME-$ENVIRONMENT.git $GITHUB_SHA:master
      - name: Deploy to Heroku
        uses: AkhileshNS/heroku-deploy@v3.0.2
        with:
          # This will be used for authentication. You can find it in your heroku homepage account settings
          heroku_api_key: $HEROKU_API_KEY
          # Email that you use with heroku
          heroku_email: HEROKU_EMAIL
          # The appname to use for deploying/updating
          heroku_app_name: $HEROKU_APP_NAME-$ENVIRONMENT
          # An optional buildpack to use when creating the heroku application
          # buildpack: # optional
          # # The branch that you would like to deploy to Heroku
          # branch: # optional, default is HEAD
          # # Set this to true if you don't want to use --force when switching branches
          # dontuseforce: # optional
          # # Will deploy using Dockerfile in project root.
          # usedocker: # optional
          # # Set if your app is located in a subdirectory.
          # appdir: # optional, default is 

      - name: Run E2E Tests
        if: github.ref == 'refs/heads/qa'
        run: |
         heroku run npm test --app $HEROKU_APP_NAME-$ENVIRONMENT
        
