name: PipeLine
# This workflow is triggered on pushes to the repository.
on:
  pull_request:
  push:
    branches:
      - master
      - dev

jobs:
  test:
    name: Testing
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    env:
      NODE_ENV: test

    steps:
    - name: Cloning Repo
    - uses: actions/checkout@v1
