name: PipeLine
# This workflow is triggered on pushes to the repository.
on:
  pull_request:
  push:
    branches:
      - master
      - dev

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    env:
      NODE_ENV: test

    steps:
    - name: Cloning Repo
      uses: actions/checkout@v1
    - name: Install Dependencies
      run: echo "Installing Dependecies"
