name: PipeLine
# This workflow is triggered on pushes to the repository.
on:
  pull_request:
  push:
    branches:
      - master
      - dev

jobs:
  test:
    name: Testing
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    env:
      NODE_ENV: test

    steps:
    - name: Cloning Repo
      uses: actions/checkout@v1
    - name: Dependencies
      run: echo "Installing Dependecies"
    - uses: actions/setup-node@v1.1.0
    - run: npm install
    - name: Check Code Styling
    - run: npm run lint

    - name: Setup PostgreSQL
      uses: harmon758/postgresql-action@v1.0.0
      with:
        postgresql version: 11
        postgresql db: test_db
        postgresql user: dev
        postgresql password: dev
