name: Source Code CI/CD

on:
  push:
    paths: 
      - '!**.spec.js'
      - '!**.test.js'
      - '!**.md'
      - '!**.yaml'
    branches:
      - master
      - dev
  pull_request:
    branches:
      - master
      - dev

jobs:
  ci:
    runs-on: ubuntu-latest
    container:
      image: node:12
    services:
      postgres:
        image: postgres:12-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: jy95
          POSTGRES_DB: sourcecode
        ports: ["5432:5432"]
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    env:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: jy95
      POSTGRES_DB: sourcecode
      POSTGRES_HOST: postgres
    steps:
      - uses: actions/checkout@v2
      - name: Set DB Port
        env:
          POSTGRES_PORT: ${{ job.services.postgres.ports[5432] }}
        run: |
          echo "::set-env name=POSTGRES_PORT::$POSTGRES_PORT"
      - name: Install
        run: |
          npm install -g npm@latest
          npm install
      - name: Testing - Migrating & Seeding
        env:
          TEST_DATABASE_URL: 'postgresql://${{ env.POSTGRES_USER }}:${{ env.POSTGRES_PASSWORD }}@${{ env.POSTGRES_HOST }}:${{env.POSTGRES_PORT}}/${{env.POSTGRES_DB}}'
        run: |
          npm run pretest
          npm run seed
          
        
